### ISSUE TITLE
[documentation bug] Linked documentation has broken example images.

### ISSUE THREAD

**Issue by mabbonda** [sandia-minimega/igor2#2]
Multiple pages of documentation have broken images. Images redirect to an authenticated portal.

![image](https://github.com/sandia-minimega/igor2/assets/160645785/d6e4fa3c-6e17-4b46-a19d-87dfca78a2b1)

![image](https://github.com/sandia-minimega/igor2/assets/160645785/be72b56b-e2d6-4096-a84f-d139951a3aed)

IE:
https://www.sandia.gov/igor/documentation/igor-web-user-guide/
https://www.sandia.gov/igor/documentation/user-guide/getting-started/

**Comment by glattercj** [comment]
Ping - anyone still on the igor team? 😄

**Comment by afbagwell** [comment]
Yep. It's fixed.
